name: Publish to NuGet

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: '1.0.0'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # 根据你的项目调整版本
        
    - name: Restore dependencies
      run: dotnet restore src/UltraKV/UltraKV.csproj
      
    - name: Build project
      run: dotnet build src/UltraKV/UltraKV.csproj --configuration Release --no-restore
      
    #- name: Test project
    #  run: dotnet test --configuration Release --no-build --verbosity normal
      
    - name: Get version from release
      id: get_version
      run: |
        if [ "${{ github.event_name }}" == "release" ]; then
          VERSION=${{ github.event.release.tag_name }}
        else
          VERSION=${{ github.event.inputs.version }}
        fi
        # 移除 'v' 前缀（如果存在）
        VERSION=${VERSION#v}
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
        echo "Publishing version: ${VERSION}"
        
    - name: Pack NuGet package
      run: |
        dotnet pack src/UltraKV/UltraKV.csproj --configuration Release --no-build \
          -p:PackageVersion=${{ steps.get_version.outputs.VERSION }} \
          -p:Version=${{ steps.get_version.outputs.VERSION }} \
          --output ./nupkg
          
    - name: Publish to NuGet
      run: |
        dotnet nuget push ./nupkg/*.nupkg \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate